# Generated by Django 5.2 on 2025-05-09 04:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
