# Generated by Django 5.2 on 2025-05-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clubs.club'),
        ),
    ]
