# Generated by Django 5.2 on 2025-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_remove_alumni_association_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_association',
            name='file',
            field=models.FileField(default='alumni_association/Alumni_page.pdf', upload_to='alumni_association/'),
        ),
    ]
