# Generated by Django 5.2 on 2025-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_alter_alumni_association_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni_association',
            name='file',
        ),
        migrations.AddField(
            model_name='alumni_association',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='alumni_association/'),
        ),
    ]
