# Generated by Django 5.2 on 2025-04-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('result_type', models.CharField(choices=[('written', 'Written Test'), ('final', 'Final Result'), ('waiting', 'Waiting List')], max_length=20)),
                ('pdf_file', models.FileField(upload_to='results/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
