# Generated by Django 5.2 on 2025-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_admissionresult_noticeboard_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='routine_type',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='title',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='routine',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='routine',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=1),
        ),
        migrations.AlterField(
            model_name='routine',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1),
        ),
    ]
