# Generated by Django 5.2 on 2025-04-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_noticeboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('routine_type', models.CharField(choices=[('class', 'Class Routine'), ('exam', 'Exam Routine')], max_length=10)),
                ('year', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], max_length=3)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], max_length=3)),
                ('image', models.ImageField(upload_to='routines/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
