# Generated by Django 5.2 on 2025-04-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], help_text='Only required for Class Routine', max_length=1, null=True),
        ),
    ]
