# Generated by Django 5.2 on 2025-05-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_examroutine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='result_type',
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='category',
            field=models.CharField(choices=[('written', 'Written Test'), ('final', 'Final Result'), ('waiting', 'Waiting List')], default='written', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='pdf_file',
            field=models.FileField(upload_to='admission_results/'),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
