# Generated by Django 5.2 on 2025-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_admissionresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admission_results/images/'),
        ),
    ]
