# Generated by Django 5.2 on 2025-05-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_admissionresult_noticeboard_routine'),
        ('academics', '0005_routine_section'),
    ]

    operations = [
    ]
