# Generated by Django 5.2 on 2025-05-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_admissionresult_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='curriculums/')),
            ],
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
