# Generated by Django 5.2 on 2025-05-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_curriculum_delete_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='missions/')),
            ],
        ),
    ]
