# Generated by Django 5.2 on 2025-05-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_academiccalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICPCEventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='icpc_event_images/')),
                ('section_order', models.IntegerField()),
            ],
            options={
                'ordering': ['section_order'],
            },
        ),
    ]
