# Generated by Django 5.2 on 2025-05-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_notice_delete_noticeboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='routine',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='1', max_length=1),
        ),
    ]
