# Generated by Django 5.2 on 2025-05-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_routine_semester_alter_routine_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionresult',
            name='category',
            field=models.CharField(choices=[('Written', 'Written Test'), ('Final', 'Final Result'), ('Waiting', 'Waiting List')], default='written', max_length=20),
        ),
    ]
