# Generated by Django 5.2 on 2025-05-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_routine_semester_alter_routine_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('credit', models.FloatField(default=0.0)),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=15, null=True)),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=15, null=True)),
            ],
        ),
    ]
