# Generated by Django 5.2 on 2025-05-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_admissionresult_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionresult',
            name='category',
            field=models.CharField(choices=[('written', 'Written Test'), ('final', 'Final Result'), ('waiting', 'Waiting List')], default='written', max_length=20),
        ),
    ]
