# Generated by Django 5.2 on 2025-05-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_course'),
        ('academics', '0014_alter_admissionresult_category'),
    ]

    operations = [
    ]
